name: Assign a tag when a commit changes the package.json version
on:
  push:
    branches:
      - main
    paths:
      - package.json
jobs:
  tag-npm-release:
    name: Tag new npm package releases
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_PUSH }}
      - shell: bash
        run: |
          #!/bin/bash
          set -eux

          TAG="v$(cat package.json | jq -r '.version')"

          # In case only a shallow clone was done
          git fetch --tags

          if ! git tag | grep "${TAG}"; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git tag -a ${TAG} -m ${TAG}
            git push --tags
          else
            echo "'${TAG}' already exists. No action taken."
          fi
