name: Run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: robinraju/release-downloader@v1.8
        id: download
        with:
          latest: true
          tarBall: true
          zipBall: false
          out-file-path: 'release'
          extract: true

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: List directory contents
        run: ls -la release

      - name: Install dependencies
        run: |
          cd release/package
          npm install

      - name: Run Node
        run: |
          cd release/package
          node .
