name: Run

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: robinraju/release-downloader@v1.8
        id: download
        with:
          latest: true
          tarBall: true
          zipBall: false
          out-file-path: 'release'
          extract: true

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd release/package
          npm install

      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Cache lastSyncInfo
        uses: actions/cache@v2
        with:
          path: ./release/package/last-sync-info.json
          key: lastSyncInfo-${{ steps.get-date.outputs.date }}

      - name: Run Node
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_TASKS: ${{ secrets.NOTION_DB_TASKS }}
          NOTION_DB_PROJECTS: ${{ secrets.NOTION_DB_PROJECTS }}
          NOTION_DB_GOALS: ${{ secrets.NOTION_DB_GOALS }}
          TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
          TODOIST_PROJECT_ROOT: ${{ secrets.TODOIST_PROJECT_ROOT }}
          IS_GITHUB_ACTION: true
        run: |
          cd release/package
          node .
